### ISSUE TITLE
Step summaries don't display within the Bitrise workflow editor

### ISSUE THREAD

**Issue by jamieastley** [amrfarid140/bitrise-step-microsoft-teams-integration#12]
Step summaries are incorrectly set as `subtitle` values.

Currently:

```yaml
- enable_debug: false
    opts:
      title: "Enable debug logging"
      subtitle: "Toggles whether to log debug info to the build output"
```

Should instead be:

```yaml
- enable_debug: false
    opts:
      title: "Enable debug logging"
      summary: "Toggles whether to log debug info to the build output"
```
