### ISSUE TITLE
Additional test steps in bitrise.yml

### ISSUE THREAD

**Issue by jamieastley** [amrfarid140/bitrise-step-microsoft-teams-integration#18]
Should add additional Go test steps to run when Bitrise test step is executed:

```yaml
workflows:
  test:
    steps:
      - go-list: {}
      - golint: {}
      - errcheck: {}
      - go-test: {}
```
